# Generated by Django 4.1.4 on 2023-01-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Communiquons_projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("courrier", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=100)),
                ("sujet", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Soumission_client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("courrier", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=100)),
                ("sujet", models.CharField(max_length=100)),
                ("entreprise", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.TextField()),
            ],
        ),
    ]
