# Generated by Django 4.1.4 on 2023-01-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takmedia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="description2",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="sous_titre",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="sous_titre2",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="titre",
            field=models.CharField(max_length=120),
        ),
    ]
