# Generated by Django 4.1.4 on 2023-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takmedia", "0003_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="description",
            new_name="description1",
        ),
        migrations.AddField(
            model_name="blog",
            name="description3",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="description4",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
