# Generated by Django 4.1.4 on 2023-01-25 15:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takmedia", "0004_rename_description_blog_description1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=120)),
                ("body", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
