# Generated by Django 4.1.4 on 2023-01-25 22:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("takmedia", "0005_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="description1",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="description2",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="description3",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="description4",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="sous_titre2",
        ),
        migrations.AddField(
            model_name="blog",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
