# Generated by Django 4.1.4 on 2023-01-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "takmedia",
            "0006_delete_contact_delete_post_remove_blog_description1_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="sous_titre",
        ),
    ]
