# Generated by Django 4.1.4 on 2023-01-30 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takmedia", "0011_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="blogpost_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
